apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-source
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-source
  name: nginx-source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-source
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-source
    spec:
      containers:
      - image: nginx
        name: nginx-source
        volumeMounts:
          - name: pvc-source
            mountPath: "/usr/share/nginx/html"
      - name: scp-source
        image: scp:sshpass
        imagePullPolicy: IfNotPresent
        command: ['sh','-c', 'service ssh start && tail -f /dev/null']
        ports:
          - containerPort: 22
        volumeMounts:
          - name: pvc-source
            mountPath: "/usr/share/nginx/html"
volumes:
      - name: pvc-source
        persistentVolumeClaim:
            claimName: pvc-source
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-source
spec:
  ports:
    - name: web
      port: 80
    - name: scp-source
      port: 22
  selector:
    app: nginx-source